Added check to show or hide auto_ivc
OpenMDAO/OpenMDAO pull request #1680
Opened 2020-09-15 20:00 UTC by DKilkenny

### Summary

Added check to show or hide auto_ivc

### Related Issues

- Resolves #1666

### Backwards incompatibilities

None

### New Dependencies

None

2020-09-15 20:12 UTC, naylor-b requested changes

2020-09-15 20:12 UTC, naylor-b commented on openmdao/error_checking/check_config.py
> +            simple_warning(i)
instead of using a simple_warning here, you should follow what the other check functions do, which is logger.warning(...)

2020-09-15 20:12 UTC, naylor-b commented on openmdao/core/tests/test_group.py
>          with assert_warning(UserWarning, msg):
After changing the check to use the logger (see other comment), you'll have to change this test.  To see other examples, search the source for 'TestLogger'.

2020-09-16 14:29 UTC, naylor-b approved these changes

2020-09-16 15:18 UTC, Kenneth-T-Moore approved these changes

2020-09-16 18:46 UTC, merged