Tweak to balance comp for complex safeness
OpenMDAO/OpenMDAO pull request #1715
Opened 2020-10-01 23:44 UTC by JustinSGray

### Summary

I noticed that the balance comp was barking in a check_partials call on a user model. This was scary, since we rely heavily on the balance. The derivs were fine, but the complex-check was bad because we used numpy absolute value, instead of our complex safe one. 

I borrowed the cs safe complex definition from the exec-comp to fix the problem

2020-10-03 01:34 UTC, robfalck requested changes
This should be applied to EQConstraintComp as well.

2020-10-04 18:54 UTC, JustinSGray commented
@robfalck I added the change to EqConstraintComp too, but that forced me to make a separate module to hold the helper function... cause copying the helper function into three separate files seemed dumb.

2020-10-05 03:27 UTC, Kenneth-T-Moore approved these changes

2020-10-05 13:16 UTC, robfalck approved these changes

2020-10-05 13:17 UTC, merged