Poem 032 implementation (driver scaling report)
OpenMDAO/OpenMDAO pull request #1820
Opened 2021-01-07 14:14 UTC by naylor-b

### Summary

Implements a web viewer showing driver design var/obj/constraint tables and jacobian magnitude heatmap.
Adds a new command line option, 'openmdao scaling'.

### Related Issues

- Resolves #1762

### Backwards incompatibilities

None

### New Dependencies

Depends on d3.js (v6), but it's been added to the openmdao repo and is incorporated directly into the generated html file so it's not a dependency the user will have to worry about.

2021-01-07 16:05 UTC, Kenneth-T-Moore approved these changes
I played around with this on some models, and it looks good. I found that the command line doesn't work on dymos models (because they usually run with `dm.run_problem`, but you can just call the p.driver.scaling_report on those anyway, so probably not important.

2021-01-07 16:15 UTC, Kenneth-T-Moore requested changes
Turns out it might be a bug: introspection not finding run_driver call for some dymos examples (aircraft_steady_flight).

2021-01-07 16:24 UTC, Kenneth-T-Moore approved these changes
All is working correctly.

2021-01-13 14:39 UTC, robfalck approved these changes

2021-01-13 15:07 UTC, merged