Added a 2021 roadmap
OpenMDAO/OpenMDAO pull request #1823
Opened 2021-01-07 16:25 UTC by JustinSGray

2021-01-08 18:44 UTC, Kenneth-T-Moore requested changes

2021-01-08 18:44 UTC, Kenneth-T-Moore commented on roadmaps/2021roadmap.md
> +Having a flexible optimization framework is a bit of a double edges sword,
double edges -> double-edged

2021-01-12 14:27 UTC, robfalck approved these changes

2021-01-22 15:45 UTC, Kenneth-T-Moore approved these changes

2021-01-25 19:39 UTC, merged