I1682 add a display to the N2 so that if an error occurs the user some idea of what happened
OpenMDAO/OpenMDAO pull request #1838
Opened 2021-01-20 15:00 UTC by hschilling

### Summary

Currently, if there is an error in the N2 scripts on the JavaScript side, the user might just get a blank screen for the N2. This PR provides an indication of an error and also a way to get a little more info for use in debugging and reporting the issue. For minor errors, the user will still possibly see and be able to use the N2, but they will get a warning about it.

### Related Issues

- Resolves #1682 

### Backwards incompatibilities

None

### New Dependencies

None

2021-01-20 15:54 UTC, Kenneth-T-Moore requested changes

2021-01-20 15:54 UTC, Kenneth-T-Moore commented on openmdao/visualization/html_utils.py
>          """
Need to add `head_srcs` to the doc string.

2021-01-20 15:54 UTC, Kenneth-T-Moore commented on openmdao/visualization/html_utils.py
>          """
Here too.

2021-01-20 16:04 UTC, hschilling commented on openmdao/visualization/html_utils.py
>          """
Fixed. Thanks

2021-01-20 16:07 UTC, Kenneth-T-Moore approved these changes

2021-01-21 16:31 UTC, swryan approved these changes

2021-01-21 18:44 UTC, merged