Fixed a bug where units weren't simplified in the get_val methods.
OpenMDAO/OpenMDAO pull request #1849
Opened 2021-01-22 17:37 UTC by robfalck

### Summary

`get_val` now uses `simplify_unit` in `Case`, `Problem`, and `System`.
`simplify_unit` now performs the same check as `valid_unit`, and calls to `valid_unit` just before simplify unit have been removed.
After removing some seemingly redundant imports, OpenMDAO was failing to import `_full_slice` from Component.  It is now imported from the module in which it is defined (vectors.vector).

### Related Issues

- Resolves #1832

### Backwards incompatibilities

None

### New Dependencies

None

2021-01-22 17:42 UTC, naylor-b approved these changes

2021-01-22 17:55 UTC, Kenneth-T-Moore requested changes

2021-01-22 17:55 UTC, Kenneth-T-Moore commented on openmdao/utils/units.py
> +        raise ValueError(f'{_msginfo}The units {old_unit_str} are invalid.')
I think we should put single quotes around the units in the exception, so it would look like:

The units 'in' are invalid.

2021-01-22 18:38 UTC, Kenneth-T-Moore requested changes

2021-01-22 18:38 UTC, Kenneth-T-Moore commented on openmdao/core/tests/test_units.py
> +        print(str(cm.exception))
Leftover debugging.

2021-01-25 19:40 UTC, robfalck commented on openmdao/core/tests/test_units.py
> +        print(str(cm.exception))
@Kenneth-T-Moore fixed

2021-01-26 19:43 UTC, Kenneth-T-Moore approved these changes

2021-01-26 21:04 UTC, merged