Got rid of memory allocation for -identity subjacs for matrix free ExplicitComponents
OpenMDAO/OpenMDAO pull request #1863
Opened 2021-02-01 13:46 UTC by naylor-b

This is some general cleanup/renaming for internal clarity and some memory savings for matrix free explicit comps in preparation for issue 1842 (matrix free coloring).

I originally intended to get rid of memory allocation for -identity subjacs in all ExplicitComponents whether matrix free or not, but that affected too many other areas of the code so I backed those changes out, at least for now.

2021-02-01 17:36 UTC, Kenneth-T-Moore requested changes

2021-02-01 17:36 UTC, Kenneth-T-Moore commented on openmdao/core/tests/test_parallel_derivatives.py
> -                self.declare_partials('y', 'x')
I assume that, if we want to get the most efficiently total model coloring, we still need to declare the partials (maybe a component with multiple outputs where each output depends on a subset of the inputs.)  Do we still have a test in our suite where we do that?

2021-02-01 17:36 UTC, Kenneth-T-Moore commented on openmdao/core/component.py
> +                           f"partials: {sorted(self._subjacs_info)}, which will allocate "
Warning message isn't tested (though I don't remember if we test warnings rigorously.)

2021-02-03 15:34 UTC, Kenneth-T-Moore approved these changes

2021-02-03 16:07 UTC, Kenneth-T-Moore commented on openmdao/core/tests/test_parallel_derivatives.py
> -                self.declare_partials('y', 'x')
Turns out we don't support computing total model coloring when there are matrix-free comps, so I withdraw this comment.

2021-02-05 15:26 UTC, swryan approved these changes

2021-02-05 15:27 UTC, merged