Added `to_table` method to OptionsDictionary to provide `embed_options` replacement capability in Jupyter.
OpenMDAO/OpenMDAO pull request #1924
Opened 2021-02-26 01:20 UTC by robfalck

### Summary

OptionsDictionary now has a new method to_table() which can output a table representation using the tabulate package.
The __rst__() method now uses tabulate to build the underlying restructured text.
Tests for repr changed because tabulate includes two spaces between columns instead of one.

### Related Issues

None

### Backwards incompatibilities

None

### New Dependencies

tabulate is now used when building the Sphinx documentation.
It is included when pip installed with [notebooks] or [all].

2021-02-26 13:31 UTC, swryan requested changes

2021-02-26 13:31 UTC, swryan commented on openmdao/utils/tests/test_options_dictionary.py
> +    def test_to_table(self):
I think we need a `skipTest` on this in case tabulate is not installed...  and/or a test for the "tabulate not installed" message...

2021-02-26 13:31 UTC, swryan commented on openmdao/utils/options_dictionary.py
> +                  " `pip install openmdao[notebooks]`."
`tabulate` should probably be added to the `docs` optional dependencies, since it is now required to build the docs

2021-02-26 17:57 UTC, swryan approved these changes

2021-03-01 16:33 UTC, Kenneth-T-Moore approved these changes

2021-03-02 20:32 UTC, merged