Sort the list of recorded output variables
OpenMDAO/OpenMDAO pull request #1960
Opened 2021-03-15 21:56 UTC by joanibal

### Summary

I was encountering an error when I added a recorder to case with distributed variables 

Because the list of output variables wasn't sorted, different procs were trying to get the value of different distributed variables at the same time. 
https://github.com/OpenMDAO/OpenMDAO/blob/ae969b72d7fb32ac8bd78f2133d082e8619dd2cc/openmdao/core/system.py#L4681-L4692

Simply sorting the list of recorded outputs fixed the issue for me. 

### Backwards incompatibilities

None

### New Dependencies

None

2021-03-16 17:07 UTC, joanibal commented
I'm going to take another look at this. 
I really didn't expect this to cause so many test failures

2021-03-19 14:52 UTC, JustinSGray commented
@joanibal if you can give a test case, that might help us track down the problem

2021-05-07 13:51 UTC, swryan requested changes

2021-05-07 13:57 UTC, swryan commented on openmdao/core/driver.py
> +            'output': myoutputs,
also, if you have a quick test to verify the fix it would be good to have..  thanks for finding this.

2021-05-11 20:36 UTC, joanibal commented on openmdao/core/driver.py
> +            'output': myoutputs,
Unfortunately, I don't have a quick test that showcases the issue/fix. I have only encountered the issue when using larger models and couldn't replicate the error on an existing example.

Although, I have been using [the parallel DOE example](http://openmdao.org/twodocs/versions/latest/features/building_blocks/drivers/doe_driver.html#running-a-doe-in-parallel-with-a-parallel-model) with the larger models to make sure everything still worked and the problem was fixed.

2021-05-11 20:37 UTC, swryan commented on openmdao/core/driver.py
> +            'output': myoutputs,
I have a test about ready.. I will add it and get this bug fix merged.. thanks again

2021-05-12 00:51 UTC, swryan approved these changes

2021-05-13 17:45 UTC, merged