Disable USE_PROC_FILES when mpi is used in a notebook.
OpenMDAO/OpenMDAO pull request #2001
Opened 2021-04-08 20:47 UTC by Kenneth-T-Moore

### Summary

Disable USE_PROC_FILES when mpi is used in a notebook.

NOTE: 

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2021-04-12 15:08 UTC, robfalck approved these changes

2021-04-13 15:07 UTC, swryan requested changes

2021-04-13 15:07 UTC, swryan commented on openmdao/utils/mpi.py
> +from openmdao.core.notebook_mode import notebook
this should be `notebook_utils` now...

2021-04-13 16:49 UTC, swryan approved these changes

2021-04-13 16:50 UTC, merged