Added `--show_dependencies` to CLI so users can show dependencies when submitting an issue
OpenMDAO/OpenMDAO pull request #2050
Opened 2021-05-07 17:05 UTC by DKilkenny

### Summary

Added `openmdao --show_dependencies` to the cli for users to use when submitting an issue or just wanting to know their current openmdao dependencies/versions 

### Related Issues

- Resolves #2042

### Backwards incompatibilities

None

### New Dependencies

None

2021-05-10 14:57 UTC, swryan requested changes

2021-05-10 14:57 UTC, swryan commented on setup.py
> +
I think what you want here is:
```
import os
_root_path = os.path.realpath(os.path.dirname(__file__))
```
This is independent of cwd...

2021-05-10 14:57 UTC, swryan commented on openmdao/utils/om.py
> +              'Show dependency versions'),
`openmdao debug` by itself doesn't do anything...

I thought idea was to add the `--show_dependencies` argument alongside `--version` in the `openmdao_cmd()` function...

2021-05-10 14:57 UTC, swryan commented on setup.py
> +    open(_root_path + 'openmdao/__init__.py').read(),
with the above change, `_root_path` will not have the trailing '/'  so you would need to add it here

2021-05-10 15:03 UTC, swryan commented on openmdao/utils/om.py
> +            setup_path = setup_path[:setup_path.index('openmdao')]
also, in keeping with the pattern of the other command implementations, this function should probably live in a separate `utils` module...

2021-05-10 16:43 UTC, DKilkenny commented on openmdao/utils/om.py
> +            setup_path = setup_path[:setup_path.index('openmdao')]
@robfalck I'm ok with this since there would be a print statement to let users know what to do but are you ok with this?

2021-05-11 13:49 UTC, swryan requested changes

2021-05-11 13:49 UTC, swryan commented on openmdao/utils/om.py
> +        setup_path = setup_path[:setup_path.index('openmdao')]
this code can go away now..  replaced by the code above that gets the path from `openmdao.__file__` rather than using `getcwd`

2021-05-11 17:02 UTC, naylor-b approved these changes

2021-05-11 18:25 UTC, swryan commented on openmdao/utils/om.py
> +    setup_path = os.path.realpath(os.path.dirname(os.path.dirname(openmdao.__file__))) + "/"
minor detail but you don't need to add the "/" here because you are using `path.join` in the next line

2021-05-11 18:25 UTC, swryan commented on openmdao/utils/om.py
> +        setup_info = run_setup(setup_path + "setup.py", stop_after="init")
you already have `setup_file` so you don't need to reconstruct it here

2021-05-12 15:51 UTC, robfalck commented on openmdao/utils/om.py
> +            setup_path = setup_path[:setup_path.index('openmdao')]
I think the majority of users won't be using a development environment.  If this doesn't work with a normal pip install, is it worth pursuing?

2021-05-12 16:06 UTC, naylor-b commented on openmdao/utils/om.py
> +            setup_path = setup_path[:setup_path.index('openmdao')]
Good point.  Another possibility (requires python 3.8 or later) is to use importlib.metadata.  It's easy to query any distribution for its version and its requirements and it works for a regular environment or a dev environment.

2021-05-12 18:31 UTC, DKilkenny commented on openmdao/utils/om.py
> +            setup_path = setup_path[:setup_path.index('openmdao')]
I'm thinking we should cancel this then cause I think it's equally risky to assume they have python 3.8 or later

2021-05-12 18:34 UTC, naylor-b commented on openmdao/utils/om.py
> +            setup_path = setup_path[:setup_path.index('openmdao')]
you could also just check their python version and if they don't have > 3.8 tell them it won't work and to use pip freeze instead.

2021-05-12 18:40 UTC, robfalck commented on openmdao/utils/om.py
> +            setup_path = setup_path[:setup_path.index('openmdao')]
I'm sorry you put the effort into this but at this point I think we should hold off on this, at least until 3.8 becomes the minimum required version.

2021-05-12 19:05 UTC, DKilkenny commented on openmdao/utils/om.py
> +            setup_path = setup_path[:setup_path.index('openmdao')]
No worries. I'll close it for now

2021-05-12 19:05 UTC, closed without merging