Added deprecation warnings for vectorized derivatives
OpenMDAO/OpenMDAO pull request #2061
Opened 2021-05-11 15:53 UTC by naylor-b

### Summary

These deprecations will be needed after POEM 049 acceptance.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2021-05-11 17:16 UTC, JustinSGray requested changes
can we detect if they've implemented a mat-mat api (even if they never use the vectorize derivs) and throw a deprecation warning for that too? 

Belt and suspenders

2021-05-11 17:42 UTC, naylor-b commented
Done.

2021-05-11 17:49 UTC, JustinSGray approved these changes

2021-05-18 14:58 UTC, robfalck approved these changes

2021-05-18 15:40 UTC, merged