Added pyoptsparse decorator from dymos in
OpenMDAO/OpenMDAO pull request #2064
Opened 2021-05-12 15:07 UTC by DKilkenny

### Summary

Moved `require_pyoptsparse` decorator from Dymos into OpenMDAO to take advantage of this functionality without having to import Dymos. This PR needs to be merged in first before the linked PR. The linked PR to remove this decorator from Dymos is here: https://github.com/OpenMDAO/dymos/pull/595 

### Related Issues

- Resolves #2003

### Backwards incompatibilities

None

### New Dependencies

None

2021-05-12 15:09 UTC, naylor-b approved these changes

2021-05-12 15:32 UTC, swryan commented
I think maybe we should use this decorator at least once in the OpenMDAO codebase to verify it works...  probably convert the tests in `test_pyoptspartse.py`...

2021-05-12 15:48 UTC, robfalck requested changes
We need to test this in the code, or at least use it as Steve suggests, to verify that it works.

2021-05-12 19:38 UTC, swryan approved these changes

2021-05-13 15:54 UTC, robfalck approved these changes

2021-05-13 15:58 UTC, merged