Whenever get_io_metadata is called, update metadata and promoted names to account for any new i/o that was added.
OpenMDAO/OpenMDAO pull request #2106
Opened 2021-05-27 19:06 UTC by Kenneth-T-Moore

### Summary

1. Whenever get_io_metadata is called, update metadata and promoted names to account for any new i/o that was added. This only updates subsystems that have changes.
2. Added `@use_tempdirs` to some more tests to clean up some output that is dumped in the test execution directory.

### Related Issues

- Resolves #1978

### Backwards incompatibilities

None

### New Dependencies

None

2021-05-27 19:14 UTC, naylor-b commented on openmdao/core/system.py
> +                    conf_info._reset
_reset should be a function call.

2021-05-27 19:19 UTC, Kenneth-T-Moore commented on openmdao/core/system.py
> +                    conf_info._reset
Oops, fixed.

2021-05-27 19:27 UTC, naylor-b requested changes

2021-05-27 19:27 UTC, naylor-b commented on openmdao/core/system.py
> +                    conf_info._reset()
Actually I would move the _reset() call to after the self._setup_var_data, and would put the self._setup_var_data inside a `if config_info._modified_systems:` conditional so it won't get called unnecessarily.

2021-05-28 14:43 UTC, naylor-b approved these changes

2021-06-02 12:17 UTC, robfalck approved these changes

2021-06-02 14:31 UTC, merged