Fixed inconsistency of `val` vs `value` in OM
OpenMDAO/OpenMDAO pull request #2118
Opened 2021-06-04 18:07 UTC by DKilkenny

### Summary

Fixed inconsistency of `val` vs `value` in OM

### Related Issues

- Resolves #1834

### Backwards incompatibilities

None

### New Dependencies

None

2021-06-04 18:19 UTC, naylor-b approved these changes

2021-06-04 18:26 UTC, Kenneth-T-Moore approved these changes

2021-06-04 18:53 UTC, swryan requested changes

2021-06-04 18:53 UTC, swryan commented on openmdao/components/exec_comp.py
> +                    warn_deprecation("'value' will be deprecated in 4.0. Please use 'val' in the "
I think you need `self.msginfo` in this warning message to point the user to the component in question.
And I think you mean to say that the argument *is* deprecated and will be *removed* in 4.0?
Also, I think you could clean this logic up a bit by merging with the following if statement, e.g.:
```
elif 'value' in val:
    if not warned:
        warn_deprecation(f"{self.msginfo}: the 'value' argument is deprecated and will be removed in version 4.0. Please use 'val'.")
        warned = True
    val['val'] = val.pop('value')
```

2021-06-04 18:53 UTC, swryan commented on openmdao/components/exec_comp.py
> +                    dct['val'] = dct.pop('value')
not clear that this is needed?  `value` has been replaced by `val` in `kwargs2`/`meta` right?

2021-06-04 18:53 UTC, swryan commented on openmdao/components/exec_comp.py
> +                    raise RuntimeError("Cannot use 'val' and 'value' at the same time, use 'val'.")
I think you need `self.msginfo` in this warning message to point the user to the component in question.

2021-06-04 18:53 UTC, swryan commented on openmdao/core/problem.py
> +            warn_deprecation("'value' will be deprecated in 4.0. Please use 'val' in the future.")
I think you need some additional info in this warning message to point the user to the call in question
And I think you mean to say that the argument *is* deprecated and will be *removed* in 4.0?
e.g.:
```
warn_deprecation(f"{self.msginfo} when calling `set_val` on {name}, the 'value' argument is deprecated and will be removed in version 4.0. Please use 'val'.")
```

2021-06-08 20:00 UTC, robfalck approved these changes

2021-06-10 17:19 UTC, robfalck requested changes

2021-06-10 17:19 UTC, robfalck commented on openmdao/core/system.py
> +                    vals=True,
I think this should be singular `val` to match `shape`, as well as the use of `val` everywhere else in the code.

2021-06-10 17:19 UTC, robfalck commented on openmdao/core/system.py
> +                     vals=True,
Singular `val` instead of `vals` here also.

2021-06-10 17:19 UTC, robfalck commented on openmdao/recorders/case.py
> +                    vals=True,
`val` instead of `vals`

2021-06-10 17:19 UTC, robfalck commented on openmdao/recorders/case.py
> +                     vals=True,
`val` instead of `vals`

2021-06-10 18:51 UTC, DKilkenny commented on openmdao/recorders/case.py
> +                     vals=True,
Fixed

2021-06-14 12:57 UTC, robfalck approved these changes

2021-06-14 18:22 UTC, swryan approved these changes

2021-06-14 18:22 UTC, merged