Check to make sure the method and settings differs between computing derivs and checking derivs
OpenMDAO/OpenMDAO pull request #2166
Opened 2021-07-07 13:01 UTC by hschilling

### Summary

It doesn't give the user any new information if they check derivatives ( either using check_partials or check_totals, with approx ) using the same method (fd or cs) AND all the same options (step, form, step_calc, directional depending on the method ). 

This PR puts in checks for that and issues a custom OpenMDAO warning that defaults to raising an exception. 

### Related Issues

- Resolves #2114 

### Backwards incompatibilities

None

### New Dependencies

None

2021-07-07 16:11 UTC, Kenneth-T-Moore requested changes

2021-07-07 16:40 UTC, hschilling commented
Thanks. Fixed !

2021-07-07 17:23 UTC, Kenneth-T-Moore approved these changes

2021-07-07 21:24 UTC, hschilling commented on openmdao/core/tests/test_check_derivs.py
> +            return msg
Good idea. Fixed. Plus I realized that I was passing more info than I needed. I did display more info in previous versions

2021-07-08 01:20 UTC, swryan approved these changes

2021-07-08 11:46 UTC, robfalck approved these changes

2021-07-08 11:47 UTC, merged