Changed handling of seeds when computing total derivatives.
OpenMDAO/OpenMDAO pull request #2197
Opened 2021-07-26 14:43 UTC by naylor-b

### Summary

Previously (in rev mode only) we divided our seed values by the number of procs where a serial output was duplicated.  This PR moves the correction for the duplication from the beginning of the computation (where seed values are now 1), to the end of the computation, after the row of the total jacobian has been computed.  This only affects total derivatives of serial outputs in rev mode when running under MPI.

### Related Issues

- Resolves #2179

Note that issue 2179 describes a number of enhancements that were not implemented.  The initial scaling of the seed values was removed and a correction is now made to the total derivatives (rev mode only) after a row of the total jacobian is computed, but all of the previous restrictions are still in place, i.e., it is still an error if a user creates a component with distributed inputs and serial outputs if the component doesn't use the matrix free API, and the component must still do its own internal Allreduce for derivatives of serial outputs with respect to distributed inputs in the compute_jacvec_product or apply_linear methods.

### Backwards incompatibilities

None

### New Dependencies

None

2021-07-26 19:55 UTC, swryan approved these changes

2021-07-30 14:04 UTC, Kenneth-T-Moore requested changes

2021-07-30 15:56 UTC, naylor-b commented on openmdao/core/tests/test_distrib_derivs.py
> +        self.x_dist_init = x_dist_init = (3.0 + np.arange(size)[offsets[rank]:offsets[rank] + sizes[rank]]) * .1
Without the .1 the numbers get really big in the stacked case and resulted in absolute errors for fd that looked pretty big even though the relative errors were ok.

2021-07-30 16:01 UTC, naylor-b commented on openmdao/core/total_jac.py
> +            ndups = self.in_idx_map[mode][i][0]
fixed

2021-07-30 17:00 UTC, Kenneth-T-Moore approved these changes

2021-07-30 17:16 UTC, merged