Added MissingImport checks for various packages
OpenMDAO/OpenMDAO pull request #2203
Opened 2021-08-02 20:21 UTC by DKilkenny

### Summary

Added MissingImport checks for various packages

### Related Issues

- Resolves #1870

### Backwards incompatibilities

None

### New Dependencies

None

2021-08-09 16:52 UTC, swryan requested changes

2021-08-09 16:52 UTC, swryan commented on openmdao/utils/tests/test_testing_utils.py
> +class TestMissingImports(unittest.TestCase):
It looks like you are just testing the Missing Imports context manager here...

I think the intent of the Issue was to make sure that openmdao features don't blow up if some optional dependency is not installed, eg. (from the issue description):

```
    with MissingImports('IPython'):
        import openmdao.api as om
```

Just replacing all your imports below with `import openmdao.api` may be a good baseline test...  
Could maybe also try importing some class related to a specific dependency as a further test...

2021-08-12 02:17 UTC, swryan approved these changes

2021-08-16 18:03 UTC, robfalck approved these changes

2021-08-16 18:04 UTC, merged