add checks for unserializable options
OpenMDAO/OpenMDAO pull request #2225
Opened 2021-08-13 20:16 UTC by swryan

### Summary

Add a check to `openmdao check` to report any options in the model that are not serializable.

This functionality has two modes of operation:

- The default mode (`openmdao -c unserializable_options`) will flag any options that are not serializable but not set as such. Leaving these in the model would result in a serialization error during recording and result in the entire set of options for that system or solver not being recorded.  This is included when the default checks are run.

- Alternatively, (`openmdao -c all_unserializable_options`)  will warn users about _any_ options that are not serializable, and therefore won't be recorded.  This is included when `all` checks are run.

### Related Issues

- Resolves #2206

### Backwards incompatibilities

None

### New Dependencies

None

2021-08-16 13:54 UTC, robfalck approved these changes

2021-08-17 17:38 UTC, Kenneth-T-Moore requested changes

2021-08-17 17:38 UTC, Kenneth-T-Moore commented on openmdao/error_checking/check_config.py
> +        _check_opts(system.linear_solver)
A couple more to check:

`nonlinear_solver.linear_solver`
`nonlinear_solver.linesearch`

2021-08-17 19:15 UTC, Kenneth-T-Moore approved these changes

2021-08-18 10:27 UTC, merged