CaseRecorder Variable Viewer
OpenMDAO/OpenMDAO pull request #2330
Opened 2021-11-02 21:16 UTC by DKilkenny

### Summary

This PR introduces a new visualizer to OpenMDAO for users to be able to visualize the recorded aspects of their model to the progression and result of their model. Users can:
- Plot variable vs variable
- Plot variable vs variable  over a given number of cases
- Plot a variable vs case iterations (with normalization, min/max, or vector lines)
- Plot a variable vs the length of the vector 
- Explore the variables by source and inputs, outputs, and residuals

### Related Issues

- Resolves #N/A

### Backwards incompatibilities

None

### New Dependencies

None

2021-11-04 18:02 UTC, swryan reviewed
just some observations when browsing the code...

2021-11-04 18:02 UTC, swryan commented on openmdao/visualization/record_viewer.py
> +                                        unable to plot"""
looks like you will get a bunch of spaces between `values,` and `unable`... is that intentional?

2021-11-04 20:41 UTC, DKilkenny commented
Good suggestions Steve. Fixed

2021-11-08 14:32 UTC, robfalck requested changes

2021-11-08 14:32 UTC, robfalck commented on openmdao/visualization/record_viewer.py
> +"""Define the CaseViewer class."""
change filename to case_viewer.py

2021-11-10 15:37 UTC, robfalck approved these changes

2021-11-16 18:01 UTC, robfalck requested changes
Putting this on hold for now.

2021-11-17 17:20 UTC, Kenneth-T-Moore commented
You could add a section on the case viewer to the Command Line Tools doc: https://openmdao.org/newdocs/versions/latest/other_useful_docs/om_command.html

2021-11-17 17:22 UTC, Kenneth-T-Moore requested changes

2021-11-17 17:24 UTC, Kenneth-T-Moore commented
I got this warning at one point, and from then on, the plot window glitched, and I was getting frames within frames.  I wonder if there is a better way to handle this.

```
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('cases', 46), ('color', 46), ('x_vals', 8), ('y_vals', 8)```

2021-11-17 17:31 UTC, Kenneth-T-Moore commented
<img width="288" alt="z" src="https://user-images.githubusercontent.com/867917/142251258-75ab5692-3be5-4f53-b39f-7a8f09310e31.png">
A couple of things confuse me on the axis selection menus. The "Case Iterations" and "Number of Points" can be selected here, but they aren't technically OpenMDAO inputs.  I'd prefer to see those separate from inputs, maybe standalone above the inputs section.  Also, I don't know why they are also listed in the "residuals" section.

2021-12-06 21:16 UTC, Kenneth-T-Moore commented
I just pulled down the latest, and I can't get Number of Cases or Case Iterations to show up at all on the "X" axis.  Also, i can't get plot a variable vs another variable anymore. Y axis is fixed at just Cases and Iterations.

2021-12-08 22:51 UTC, Kenneth-T-Moore commented
I think that Case Iteration as the x-axis value isn't working correctly. I'd expect them all to have different x values, instead of all being 0.

<img width="717" alt="z1" src="https://user-images.githubusercontent.com/867917/145304012-9bf7b872-f360-4934-9024-782fb42c5c1c.png">

2021-12-10 21:34 UTC, Kenneth-T-Moore reviewed
Things are working smoothly now.

2021-12-10 21:34 UTC, Kenneth-T-Moore approved these changes

2022-01-27 22:29 UTC, JustinSGray approved these changes
Im approving this PR. I think its not quite ready for release, but the things Danny developed are complete enough to merge. 

Further development can be handled by subsequent PRs

2022-02-10 20:14 UTC, ehariton commented
Below are some interface revision suggestions.

Original Implementation:
![view_cases_original](https://user-images.githubusercontent.com/11527849/153454862-f92259bd-6bf7-4940-8377-a15fb5b3ccf7.png)

Revised Implementation:
![view_cases](https://user-images.githubusercontent.com/11527849/153457350-2cdca4d9-9f88-478f-a078-282f1f32ee66.png)

- Case Selection should be limited to `First`, `Last`, `All`, or `Other`, using a single item selection box. If Other is checked, the sliders along the bottom, which are normally greyed out, should become active and allow the user to slide left and right to make a selection. The original implementation allowed the user to select using the whole word string for that iteration (`rank0.pyOptSparse_SNOPT|1`), which is unnecessarily detailed.  
- X Values & Y Values should have input boxes that allow users to filter the drop down menu to only those items of interest. This is especially important because typically the users knows "I want to graph alpha in ascent". But the user doesn't necessarily remember the full path name for it. Displaying the sub-set of options that contain the search term will assist the user in quickly identifying the full path name.
- Case Iteration Plot Options should be renamed to Options for simplicity. Single item selection box should be used to select one of the three valid options. There are not that many options here so using a drop-down list seems overkill. 
- Help Icon on the bottom right corner that opens up examples. This should have at least two examples showing how to make a graph of a single-variable control and graph it over the major iterations, and a graph of a vector control graphed over all the major iteration. We may also want to include here an example of ill-posed problems that don't converge vs. well-posed problems that do converge as a reminder to the user of things that might be of interest. 
- If we want users to be able to select major iterations that are not sequential (e.g. 4, 8, 27) then we may need an additional "Advanced Options" that brings up the original interface which can allow for such selections.

2022-03-16 17:54 UTC, robfalck commented
Superseded by #2470, which combines the ideas in this PR with jupyter widgets for now.

2022-03-16 17:54 UTC, closed without merging