Poem059 - Unitless & Percent Quantities
OpenMDAO/OpenMDAO pull request #2340
Opened 2021-11-15 22:54 UTC by andrewellis55

### Summary

PR for PEOM 059

### Backwards incompatibilities

None

### New Dependencies

None

2021-11-18 20:42 UTC, robfalck requested changes
Needs some minimal tests in the codebase to verify that it's working.

2021-11-19 16:18 UTC, andrewellis55 commented
@robfalck Tests have been added.

2021-11-19 16:20 UTC, robfalck approved these changes

2021-11-22 15:36 UTC, Kenneth-T-Moore approved these changes

2021-11-23 18:33 UTC, merged