Added clarity to error msg for shape mismatch during setup
OpenMDAO/OpenMDAO pull request #2353
Opened 2021-11-22 14:54 UTC by DKilkenny

### Summary

Added the target name to the error msg in `_get_auto_ivc_out_val` which showed up during setup.

### Related Issues

- Resolves #2316 

### Backwards incompatibilities

None

### New Dependencies

None

2021-11-22 15:27 UTC, naylor-b approved these changes

2021-11-22 15:28 UTC, Kenneth-T-Moore approved these changes

2021-11-22 15:41 UTC, robfalck approved these changes

2021-11-22 15:49 UTC, swryan commented on openmdao/core/group.py
> +                                         f"{value.shape} into shape {val.shape}.")
seems like there are other possible `ValueError` messages that could occur...  
Maybe you should just prefix whatever error comes back, e.g.: 
https://github.com/OpenMDAO/POEMs/blob/master/POEM_058.md?plain=1#L121

2021-11-22 16:47 UTC, swryan requested changes
see comment...  pass through actual error message

2021-12-01 18:49 UTC, swryan approved these changes

2021-12-01 18:49 UTC, merged