Changed Deprecation to OM Warning For Serial to Distributed IO Connections
OpenMDAO/OpenMDAO pull request #2363
Opened 2021-11-29 18:03 UTC by DKilkenny

### Summary

Removed the deprecation and changed to a OM warning to keep the functionality but alert the user to verify the connections.

### Related Issues

- Resolves #2346

### Backwards incompatibilities

None

### New Dependencies

None

2021-11-29 19:52 UTC, naylor-b requested changes

2021-11-29 21:17 UTC, DKilkenny commented on openmdao/core/tests/test_group.py
> +    def test_serial_input_to_distrib_output(self):
fixed

2021-12-02 17:59 UTC, naylor-b commented on openmdao/core/group.py
> +                    issue_warning(f"Connecting a serial output '{abs_out}' and distributed input "
What exactly are we asking the user to do here?  If I were a user and saw this message I would be worried that something was wrong but would have no idea what the 'expected' connections would be.  I wonder if we should even warn the user at all if we're not going to provide them with any useful information.

2021-12-13 13:49 UTC, robfalck approved these changes

2021-12-15 14:45 UTC, naylor-b approved these changes

2021-12-15 15:09 UTC, swryan requested changes
I think we should change to description of the PR to match what was ultimately done (e.g. for the release notes) and also add a comment to the issue explaining the outcome to the original poster

2021-12-15 15:09 UTC, swryan commented on openmdao/core/tests/test_group.py
> +    DistributedComponentWarning
new import no longer needed?

2021-12-15 16:01 UTC, DKilkenny commented on openmdao/core/tests/test_group.py
> +    DistributedComponentWarning
Removed

2021-12-15 16:12 UTC, swryan approved these changes

2021-12-15 16:27 UTC, merged