refactored handling of promoted src_indices and fixed some mpi issues.
OpenMDAO/OpenMDAO pull request #2455
Opened 2022-03-02 20:49 UTC by naylor-b

### Summary

The code that handles src_indices based on connections, promotions, and group input defaults was partially re-written to both make the code more understandable and to fix issues #2442 and #2429.

In the process of running and debugging a large model containing dymos and pyCycle systems, a couple of mpi issues were also discovered and fixed.

1) __eq__ and __hash__ methods were added to _ReprClass because in an MPI environment it's possible to have more than one instance of a given _ReprClass constant where the instances are not the same object but should be treated as equivalent.
2) In _ordered_comp_name_iter, it was returning duplicate system names when running across multiple MPI processes.

### Related Issues

- Resolves #2441
- Resolves #2429

### Backwards incompatibilities

None

### New Dependencies

None

2022-03-04 21:23 UTC, Kenneth-T-Moore requested changes

2022-03-04 21:31 UTC, naylor-b commented on openmdao/api.py
> +wing_dbg()
This doesn't do anything unless WING_DBG is set in the environment.  If people really don't like it I can take it out, but it makes debugging MPI stuff more convenient.

2022-03-04 21:55 UTC, Kenneth-T-Moore approved these changes

2022-03-08 15:38 UTC, robfalck approved these changes

2022-03-08 15:42 UTC, merged