refactor of _apply_linear/_solve_linear and block linear solvers
OpenMDAO/OpenMDAO pull request #2534
Opened 2022-05-25 18:33 UTC by naylor-b

### Summary

When nested groups had block linear solvers (LinearBlockGS and LinearBlockJac), there were unnecessary _apply_linear calls being made on components under those groups.  

The _solve methods of the block linear solvers were modified so that direct calls to _apply_linear on subsystems would only be called if those subsystems were either components or were groups not being solved by block linear solvers themselves.  Additional args were added to _solve_linear so that the variables relevant to a block linear solve could be passed down the system tree, accumulating at each group level until (possibly) reaching a component.  This allows a component _apply_linear to execute only once in a given recursive block linear solve where the set of 'relevant' variables will be the full set from the group originating the linear solve down the tree to the component, instead of the old way, where the component apply linear would be called once for each group level linear solve, with different 'relevant' variables at each level.

The issue this PR is based on, #2405, described using caching to avoid unnecessary computations in compute_jacvec_product or apply_linear, but it was determined that we could refactor _apply_linear/_solve_linear instead and the caching wouldn't be required.

### Related Issues

- Resolves #2405

### Backwards incompatibilities

None

### New Dependencies

None

2022-05-31 14:48 UTC, Kenneth-T-Moore requested changes

2022-05-31 14:48 UTC, Kenneth-T-Moore commented on openmdao/vectors/vector.py
> +    def get_hash(self, alg=hashlib.sha1):
I don't think this method is used anywhere.

2022-05-31 15:30 UTC, Kenneth-T-Moore approved these changes

2022-06-21 18:57 UTC, robfalck approved these changes

2022-06-21 19:02 UTC, merged