updated check for when coloring doesn't meet min improvement percentage
OpenMDAO/OpenMDAO pull request #2630
Opened 2022-09-06 19:10 UTC by naylor-b

### Summary

When computing total coloring, we were accessing the wrong member of the tuple returned from Coloring._solves_info() so we were comparing the min improvement percentage to the wrong thing.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2022-09-08 13:39 UTC, Kenneth-T-Moore requested changes

2022-09-15 14:58 UTC, naylor-b commented on openmdao/core/driver.py
> +                    self._coloring_info['coloring'] = self._coloring_info['coloring'] = None
Not sure how that got in there.  Fixed.

2022-09-15 15:04 UTC, Kenneth-T-Moore approved these changes

2022-09-15 16:27 UTC, swryan approved these changes

2022-09-15 16:27 UTC, merged