Changed ImplicitComponent.apply_nonlinear() to raise NotImplementedError
OpenMDAO/OpenMDAO pull request #2664
Opened 2022-10-12 17:43 UTC by tadkollar

### Summary

Instead of just calling `pass`, `apply_nonlinear()` now raises NotImplementedError.

### Related Issues

- Resolves #2660

### Backwards incompatibilities

None

### New Dependencies

None

2022-10-13 17:08 UTC, Kenneth-T-Moore requested changes

2022-10-13 17:08 UTC, Kenneth-T-Moore commented on openmdao/core/implicitcomponent.py
> +        raise NotImplementedError('ImplicitComponent.apply_nonlinear() must overridden '
must overridden -> must be overridden

2022-10-13 17:08 UTC, Kenneth-T-Moore commented on openmdao/core/implicitcomponent.py
>          """
Need a test for this error message.

2022-10-14 16:36 UTC, robfalck approved these changes

2022-10-14 16:42 UTC, Kenneth-T-Moore approved these changes

2022-10-15 01:48 UTC, merged