Consider relevance information when running _linearize
OpenMDAO/OpenMDAO pull request #2675
Opened 2022-10-18 13:40 UTC by naylor-b

### Summary

Group._linearize now only calls _linearize on relevant subsystems.

### Related Issues

- Resolves #2674

### Backwards incompatibilities

An additional arg, `rel_systems`, was added to Group._linearize.  This is not a user facing method so it shouldn't cause problems.

### New Dependencies

None

2022-10-18 15:05 UTC, Kenneth-T-Moore requested changes

2022-10-19 17:06 UTC, naylor-b commented on openmdao/core/total_jac.py
> +        self.total_relevant_systems = set()
fixed

2022-10-19 17:53 UTC, Kenneth-T-Moore approved these changes

2022-10-25 17:00 UTC, robfalck approved these changes

2022-10-26 12:01 UTC, merged