POEM 74: Suggest variables close in name on failed
OpenMDAO/OpenMDAO pull request #2681
Opened 2022-10-22 19:51 UTC by joanibal

### Summary
This PR is associated with POEM 74: Suggest variables close in name on failed connection attempt. 

### Related Issues

None

### Backwards incompatibilities

None. It only changes error messages

### New Dependencies

The python built-in difflib

2022-10-25 18:01 UTC, naylor-b requested changes

2022-10-25 18:01 UTC, naylor-b commented on openmdao/core/group.py
> +                          f"'{prom_in}', but '{prom_out}' doesn't exist.Perhaps you ment to connect to one of the following outputs:{guesses}"
ment --> meant (also occurs below)

2022-10-26 12:14 UTC, robfalck requested changes

2022-10-31 20:09 UTC, joanibal commented
Thanks for the grammar fixes @johnjasa

2022-10-31 20:12 UTC, joanibal commented
It appears I can only add a re-review request to one reviewer

2022-10-31 20:17 UTC, naylor-b approved these changes

2022-10-31 20:36 UTC, johnjasa commented
@joanibal will you be able to address these test failures? I can take a stab if you prefer. I think it's just pep8 and an error message test for your updated message.

2022-11-01 16:04 UTC, joanibal commented
The tests now seem to be failing for reasons unrelated to the PR.
Did something in the CI pipeline change?

On Ubuntu_minmal the error is related to the `open` function (possibly related to the python 3.11 update?)
```
   File "/usr/share/miniconda/envs/test/lib/python3.11/site-packages/openmdao/devtools/iprof_utils.py", line 80, in find_qualified_name
    with open(filename, 'Ur') as f:
         ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'Ur'
```

The other platforms are failing the dependency audit 
```
Found 1 known vulnerability, ignored 2 in 1 package
Name         Version ID                  Fix Versions
------------ ------- ------------------- ------------
jupyter-core 4.11.1  GHSA-m678-f26j-3hrp 4.11.2
```
or can't pip install jax
```
Collecting jax
  Downloading jax-0.3.23.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 27.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
ERROR: Could not find a version that satisfies the requirement jaxlib (from versions: none)
ERROR: No matching distribution found for jaxlib
```

2022-11-02 15:18 UTC, swryan commented
@joanibal  you should be good to sync your PRs up with the master branch now..  the GitHub workflow has been updated.

Thanks for your patience.

2022-11-12 18:21 UTC, robfalck approved these changes

2022-11-13 00:21 UTC, merged