Directional check_totals
OpenMDAO/OpenMDAO pull request #2859
Opened 2023-03-21 14:55 UTC by naylor-b

### Summary

Implements POEM 76, which adds a 'directional' arg to check_totals.

The output of check_totals/check_partials was also updated to more accurately reflect whether the Jacobians in question were computed in fwd or rev mode.

### Related Issues

- Resolves #2814

### Backwards incompatibilities

None

### New Dependencies

None

2023-03-23 20:14 UTC, Kenneth-T-Moore approved these changes

2023-04-24 18:10 UTC, swryan commented
requesting re-review from Ken pending his investigation into the Aviary use case

2023-04-25 14:26 UTC, Kenneth-T-Moore requested changes
I've submitted a minimal model to Bret that shows a bug in the directional reverse-mode dot-product.

2023-04-25 20:14 UTC, Kenneth-T-Moore approved these changes

2023-04-26 13:16 UTC, swryan approved these changes

2023-04-26 13:16 UTC, merged