Implemented a way of getting all independent variables from a Problem.
OpenMDAO/OpenMDAO pull request #2871
Opened 2023-03-29 16:14 UTC by robfalck

### Summary

User's often need a succinct list of the variables they are expected to provide for a problem.  As the complexity of models grows, it can be easy to overlook an input to the problem.

This PR addresses this by adding a `Problem.get_indep_vars` method. This method returns any variable tagged with `'openmdao:is_indep_var'`. This allows the inclusion of both IndepVarComp outputs and outputs from user models with IndepVarComp-like behavior.

The method allows for optional exclusion of design variables from the returned list.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2023-03-29 17:11 UTC, Kenneth-T-Moore commented on openmdao/core/problem.py
> +            prom = model._var_allprocs_abs2prom['input'][target]
This line is superfluous.

2023-03-30 17:25 UTC, naylor-b requested changes

2023-03-30 17:25 UTC, naylor-b commented on openmdao/core/problem.py
> +        to provide components with IndepVarComp-like capaability.
typo: capaability

2023-03-30 17:25 UTC, naylor-b commented on openmdao/core/problem.py
> +        desvar_prom_names = set(model.get_design_vars(recurse=True, use_prom_ivc=True).keys())
May want to add a `get_sizes=False` arg to the `get_design_vars` call since you only want the names.

2023-03-30 17:25 UTC, naylor-b commented on openmdao/core/problem.py
> +        desvar_prom_names = set(model.get_design_vars(recurse=True, use_prom_ivc=True).keys())
You don't really need to create a set here.  The dict returned from model.get_design_vars should give you what you need to do  quick checks to see if a var is a DV.

2023-04-03 14:14 UTC, Kenneth-T-Moore approved these changes

2023-04-03 14:14 UTC, naylor-b approved these changes

2023-04-03 17:08 UTC, merged