Added release notes for 3.26.0
OpenMDAO/OpenMDAO pull request #2880
Opened 2023-04-06 15:47 UTC by robfalck

### Summary

Adds release notes for pending 3.26.0 release.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2023-04-07 15:11 UTC, swryan commented on release_notes.md
>  # Release Notes for OpenMDAO 3.25.0
3.26.0

2023-04-13 15:28 UTC, Kenneth-T-Moore requested changes

2023-04-13 15:28 UTC, Kenneth-T-Moore commented on release_notes.md
> +- Refactor for complex step around Newton. [#2839](https://github.com/OpenMDAO/OpenMDAO/pull/2839)
"Refactor for complex step around Newton" --> Refactored how complex-step was performed around a Newton solver to address an accuracy problem.

2023-04-14 13:28 UTC, swryan approved these changes

2023-04-14 16:34 UTC, merged