Fix for a bug found when computing semi-total derivatives.
OpenMDAO/OpenMDAO pull request #2885
Opened 2023-04-12 20:13 UTC by naylor-b

### Summary

When computing the approx subjac keys it was looping over promoted input names and only taking the first absolute input name in the list, causing perturbations not to propagate correctly through implicitly connected inputs.

Also fixed a logic error when weeding out candidate wrt's that didn't connect to IndepVarComp outputs.  An absolute component name was being computed from the absolute var name and used in a call to `_get_subsystem`, but `_get_subsystem` requires a relative name, so IndepVarComps were actually being missed.  After this was fixed, a test failed because `_jac_wrt_iter` was now yielding the same name twice.  The duplication was removed and now all tests pass.

### Related Issues

- Resolves #2874

### Backwards incompatibilities

None

### New Dependencies

None

2023-04-13 17:05 UTC, Kenneth-T-Moore requested changes
Awaiting change to _var_allprocs_abs2meta in line 2850. Looks good otherwise.

2023-04-13 17:32 UTC, robfalck approved these changes

2023-04-14 11:50 UTC, dingraha commented
This appear to fix the problem I was having with using `approx_totals`, but it also appears to require many more `compute` calls than I expected. I've attached an example that is similar to the actual application I'm working on. When I use this PR, running `run_model` and then `compute_totals` requires 25 `compute` calls, judging from the print statements I added to one of the components. When I try with OpenMDAO `3.25.0` it only requires 5 `compute` calls. I'm asking for derivatives with respect to two inputs from the `Group` with `approx_totals`, so I would have expected the `compute_totals` to require 3 compute calls (2 calls to perturb each input, 1 for the unperturbed inputs, 1 for a `compute` call that I imagine `compute_totals` does just to be safe, and then 1 more for the `run_model` that I have in the script just before `compute_totals`). Maybe I'm misunderstanding how `approx_totals` is supposed to work?

Here is the script (actually a Python script, just added the `txt` extension for GitHub):

[mwe2.py.txt](https://github.com/OpenMDAO/OpenMDAO/files/11232378/mwe2.py.txt)

2023-04-14 18:58 UTC, naylor-b commented
@dingraha I pushed up a fix.  If you get a chance, please try it out and let me know if your issue is fixed.

2023-04-14 19:25 UTC, dingraha commented
@naylor-b Working on it, thanks! Seems to work for the MWE, checking it on the "real" test case now...

2023-04-14 19:43 UTC, dingraha commented
@naylor-b This seems to fix my issue. :-)

How hard would it be to test how many times `compute` is called when using `approx_totals` (if that's not done already)?

2023-04-17 18:39 UTC, Kenneth-T-Moore approved these changes

2023-04-18 16:45 UTC, merged