Updated documentation of guess_nonlinear method to use run_apply_nonlinear.
OpenMDAO/OpenMDAO pull request #2899
Opened 2023-04-25 19:07 UTC by robfalck

### Summary

In the documentation of `guess_nonlinear`, the residuals were not in sync with the inputs.  Testing the residuals to see if they were acceptably small before applying a new guess for the implicit output was therefore not testing an accurate value of the residual.

This change fixes the example so that it tests all residuals in the system, which seems to be a more reliably way checking to see if the system is close to convergence.

### Related Issues

- Resolves #2898 

### Backwards incompatibilities

None

### New Dependencies

None

2023-04-26 14:03 UTC, naylor-b requested changes

2023-04-26 14:03 UTC, naylor-b commented on openmdao/docs/openmdao_book/features/core_features/working_with_groups/guess_method.ipynb
> +    "        if np.any(np.abs(list(residuals.values())) > 1.0E-2):\n",
residuals.asarray() would be more efficient than list(residuals.values()).

2023-04-26 18:34 UTC, swryan commented
The example from the docs also exists as a unit test [here](https://github.com/OpenMDAO/OpenMDAO/blob/e505204893261ea5de0684ed01e640eca2eb7c96/openmdao/core/tests/test_group.py#L3939).

That test should probably be updated, or possibly just deleted as redundant.

2023-05-03 14:41 UTC, naylor-b approved these changes

2023-05-03 14:55 UTC, Kenneth-T-Moore approved these changes

2023-05-03 16:10 UTC, merged