Possible solution to POEM_085
OpenMDAO/OpenMDAO pull request #2925
Opened 2023-05-22 22:11 UTC by crecine

Added capability for results to be exported as csv instead of html.

### Summary

Expand view_connections to check file extension for html or csv.
This allows for formatting the export of the data automatically.

### Related Issues

- Resolves # 2924

### Backwards incompatibilities

None

### New Dependencies

None

2023-05-23 13:42 UTC, Kenneth-T-Moore requested changes

2023-05-23 13:42 UTC, Kenneth-T-Moore commented on openmdao/visualization/connection_viewer/viewconns.py
> +    elif '.csv' in outfile:
You should also add a test for the sake of code coverage. We don't test the  contents of the html file that is generated, but we do run it just to make sure there isn't an error: https://github.com/OpenMDAO/OpenMDAO/blob/777a589a88f0386d0d393ee0e5f028da1a7dfb64/openmdao/visualization/connection_viewer/tests/test_viewconns.py

2023-05-23 13:42 UTC, Kenneth-T-Moore commented on openmdao/visualization/connection_viewer/viewconns.py
> +    Generate a self-contained html (or csv) file containing a detailed connection viewer.
Having "self-contained" followed by "containing" seems redundant. I know you didn't add it, but I would remove it.

2023-05-23 16:30 UTC, swryan commented on openmdao/visualization/connection_viewer/viewconns.py
> +    if '.html' in outfile:
These if statements should probably look like:
```
if outfile.endswith('.html'):
    ...
elif outfile.endswith('.csv'):
    ...
else
    raise RuntimeError("Invalid file extension for output file, should be '.html' or '.csv'")
```
(and per Ken's comment, there should be test coverage for the two new branches)

2023-05-23 16:31 UTC, swryan commented on openmdao/visualization/connection_viewer/viewconns.py
> +        The name of the output file.  Defaults to 'connections.html'.
should note here or in the summary that the output file format is determined by the file extension

2023-05-24 17:21 UTC, swryan approved these changes

2023-06-02 18:34 UTC, merged