Renamed `list_problem_vars` to `list_driver_vars`
OpenMDAO/OpenMDAO pull request #3132
Opened 2024-02-22 22:24 UTC by robfalck

### Summary

Method `list_problem_vars` is ambiguous and is renamed to `list_driver_vars`.
It will remain as a deprecated for now.

### Related Issues

- Resolves #2872 

### Backwards incompatibilities

None

### New Dependencies

None

2024-02-22 22:26 UTC, swryan approved these changes

2024-02-29 15:53 UTC, Kenneth-T-Moore approved these changes

2024-02-29 15:55 UTC, swryan commented
I just realized there's a doc page that should be updated for this change as well:
https://openmdao.org/newdocs/versions/latest/features/debugging/listing_variables.html?highlight=list_problem_vars

2024-02-29 15:57 UTC, swryan requested changes
need to update documentation

https://openmdao.org/newdocs/versions/latest/features/debugging/listing_variables.html?highlight=list_problem_vars

2024-02-29 17:37 UTC, swryan approved these changes

2024-02-29 18:32 UTC, merged