Updates for NumPy 2.0 compatibility and testing
OpenMDAO/OpenMDAO pull request #3241
Opened 2024-05-20 14:53 UTC by swryan

### Summary

- Updated the `Latest` workflow to test NumPy 2.0 pre-release separately (excluding PETSc and pyOptSparse)
- Added NumPy 2.0 compatibility check to the `Tests` workflow
- Fixed several NumPy 2.0 compatibility issues on The OpenMDAO codebase
  - Replaced `NaN` with `nan`
  - Updated `ComplexWarning` imports to use new location
  - Changed `array(copy=False)` to `asarray()`, which will not copy if the object is already a numpy array
  - Updated tests to handle change in the default print format
  - Updated the `cs_safe.abs()` method to preserve current numpy<2 logic for the `sign` operation

### Related Issues

- Resolves #3240

### Backwards incompatibilities

None

### New Dependencies

None

2024-05-21 15:39 UTC, robfalck requested changes

2024-05-21 15:39 UTC, robfalck commented on openmdao/utils/cs_safe.py
> +        if np.__version__[0] == '2' and np.any(np.iscomplex(x)):
Rather than do string matching here, do it at import and save a bool.

2024-05-22 16:01 UTC, robfalck approved these changes

2024-05-22 18:52 UTC, Kenneth-T-Moore approved these changes

2024-05-22 19:33 UTC, merged