Added InputResidsComp to the list of components. Added `setup_residuals` method for compatibility with dynamic shaping.
OpenMDAO/OpenMDAO pull request #3295
Opened 2024-07-15 21:08 UTC by robfalck

### Summary

Adds `InputResidsComp` to the list of OpenMDAO components.
`InputResidsComp` reduces boilerplate necessary to implement a simple implicit system by treating the added inputs as residual values.

This takes advantage of renamed residuals to allow the `InputResidsComp` to have a different number of inputs (residuals) and implicit outputs (states) so long as the total size of the inputs and outputs is equal.

To make `InputResidsComp` compatible with dynamic shaping, a new `setup_residuals` method was added that allows for the addition of residuals during final setup, once the sizes of inputs and outputs has been determined. Overriding `setup_residuals` in an explicit component will result in an error.

### Related Issues

- Resolves #3294

### Backwards incompatibilities

None

### New Dependencies

None

2024-07-16 12:29 UTC, naylor-b requested changes

2024-07-16 12:29 UTC, naylor-b commented on openmdao/components/input_resids_comp.py
> +        self.mat = np.eye(size) * 3.
self.mat doesn't appear to be used anywhere

2024-07-16 12:29 UTC, naylor-b commented on openmdao/components/input_resids_comp.py
> +            size = self._get_var_meta(name, 'size')
Since you already have the relative name, it would be quicker to just get size from self._var_rel2meta[name]['size']

2024-07-17 16:39 UTC, swryan approved these changes

2024-07-17 16:47 UTC, naylor-b approved these changes

2024-07-17 16:48 UTC, merged