Added a `require_connection` argument to `add_input`
OpenMDAO/OpenMDAO pull request #3353
Opened 2024-09-18 12:09 UTC by swryan

### Summary

Added a `require_connection` argument to `add_input`.   If the input is not connected at `setup` time, an Exception is generated.

### Related Issues

- Resolves #3280

### Backwards incompatibilities

None

### New Dependencies

None

2024-09-18 12:30 UTC, naylor-b requested changes

2024-09-18 12:30 UTC, naylor-b commented on openmdao/core/tests/test_group.py
> +    def test_unconnected_input_required_connection(self):
I didn't see it but might be good to have a test for when the variable isn't connected but is declared as a design variable.

2024-09-18 12:30 UTC, naylor-b commented on openmdao/core/component.py
> +            If True, this input must be connected to an output.
I would modify the description to include being declared as a design variable.

2024-09-18 21:26 UTC, robfalck requested changes

2024-09-18 21:26 UTC, robfalck commented on openmdao/core/group.py
>          self._setup_connections()
OpenMDAO [allows connections to be issued in configure](https://openmdao.org/newdocs/versions/latest/theory_manual/setup_stack.html#usage-of-setup-vs-configure), so this check should happen at the end of configure.

2024-09-19 13:21 UTC, robfalck approved these changes

2024-09-23 18:24 UTC, merged