AnalysisDriver
OpenMDAO/OpenMDAO pull request #3365
Opened 2024-09-26 16:50 UTC by robfalck

### Summary

Adds AnalysisDriver to the list of available drivers.

AnalysisDriver is a more functional form of DOEDriver.
DOEDriver automatically samples points from the design variables and records the outputs.
AnalysisDriver allows the user to explicitly specify inputs via a sample. 
These inputs do not need to be design variables in the model, but the model does check that they are either unconnected inputs (provided by IndepVarComps) or that they are implicit outputs (in which case the initial value provides a guess for the nonlinear solvers).

To easily generate cases, the `AnalysisGenerator` serves as a base class for (currently) two generators, `ProductGenerator` and `ZipGenerator`.  ProductGenerator uses `itertools.product` to provide every possible combination of given inputs to be executed. ZipGenerator uses `zip` to provide pairs from various lists of sample values.

For instance, given a sequence of values for `x` as `[0, 1, 2]` and values for `y` as `[8, 9, 10]`, the `ProductGenerator` would produce 9 cases: `[[0, 8], [0, 9], [0, 10], [1, 8], [1, 9], [1, 10], [2, 8], [2, 9], [2, 10]` while `ZipGenerator` would produce 3 cases: `[[0, 8], [0, 9], [0, 10]]`. These are lazy, pythonic generators that do not realize all possible combinations in memory, so in theory extremely large combinations of variables will be possible now.

For now, `add_response` has been added to `AnalysisDriver` to allow the user to specify an output of interest that may not already be an objective or constraint in the model.

** Note: This is a draft PR provided for review/comment and under active development **

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2025-02-03 14:51 UTC, swryan submitted a review, later dismissed

2025-02-03 14:51 UTC, swryan commented on openmdao/drivers/analysis_generator.py
> +        keys are the arguments to `set_val`.
and whose *_values_* are the arguments to `set_val`

2025-02-03 14:51 UTC, swryan commented on openmdao/drivers/tests/test_analysis_driver.py
> +    # def test_beam_np4(self):
are you keeping this around for some future work?  should explain or delete...

2025-02-03 14:51 UTC, swryan commented on openmdao/drivers/analysis_driver.py
> +        prob.driver.add_responses(['foo', 'bar', 'baz'])
`add_reponse` is a `System` method, not `Driver` method...

2025-02-03 14:53 UTC, naylor-b requested changes

2025-02-03 14:53 UTC, naylor-b commented on openmdao/docs/openmdao_book/features/building_blocks/drivers/analysis_driver.ipynb
> +    "                  'y': {'vals': [4.0, 5.0, 6.0], units=None})\n",
I know you mention it later that variables can have different numbers of values, but might be even better to actually have x and y have different numbers of vals in this example.

2025-02-03 14:53 UTC, naylor-b commented on openmdao/docs/openmdao_book/tests/test_jupyter_output_linting.py
> +                    json_data = json.loads(data)
Just curious, why load the file into a string then convert string to json vs. just loading json from the file?

2025-02-03 14:53 UTC, naylor-b commented on openmdao/drivers/analysis_driver.py
> +        # Non-model-inputs would just have their value overridden when evaluating the model.
Non-model-inputs is somewhat confusing.  Aren't we really talking about inputs connected to IVCs?

2025-02-03 14:53 UTC, naylor-b commented on openmdao/drivers/analysis_driver.py
> +                            job_queues[rank_idx].appendleft((sample_num, sample))
In a later version we might want to revisit how we're distributing the jobs to avoid losing the 'laziness' of some of the generators.

2025-02-03 14:53 UTC, naylor-b commented on openmdao/drivers/analysis_driver.py
> +                    for i, sample in enumerate(self._samples):
I was under the impression that the self._samples would act like a normal iterable, but if that's the case then this while loop would keep resetting the iterator after each batch since a normal iterable resets at the beginning of a for loop.  Maybe the AnalysisGenerators handle this properly but we also allow lists and tuples as self._samples so it seems like this could be a problem.

2025-02-03 16:30 UTC, Kenneth-T-Moore commented on openmdao/drivers/analysis_driver.py
> +        prob.driver.add_response('z', units='m')
I kind of thought we tended to avoid putting code blocks in the OpenMDAO docstrings, since they are difficult to test.

2025-02-04 14:25 UTC, robfalck commented on openmdao/drivers/analysis_driver.py
> +        # Implicit outputs can override the value given in the case, but it might be a
Right. They're allowed because you'd want to provide a guess, but the value coming from the analysis driver will be overridden when the model executes.

2025-02-04 18:34 UTC, robfalck commented on openmdao/drivers/analysis_driver.py
> +        prob.driver.add_response('z', units='m')
Good point, will remove.

2025-02-04 18:41 UTC, robfalck commented on openmdao/docs/openmdao_book/tests/test_jupyter_output_linting.py
> +                    json_data = json.loads(data)
Just an oversight on my part, will fix.

2025-02-04 20:40 UTC, robfalck commented on openmdao/drivers/analysis_driver.py
> +        if isinstance(samples, (list, tuple, AnalysisGenerator)):
I was thinking I didn't want to worry about these being recorded, but drivers don't record their options anyway.  I'll change it.

2025-02-05 01:45 UTC, robfalck commented on openmdao/drivers/analysis_driver.py
> +        prob.driver.add_response('z', units='m')
@swryan regarding this being a system method, for the purpose of the AnalysisDriver it seems like its more natural to interact with the driver and tell it what should be recorded, rather than the system.

2025-02-05 01:51 UTC, swryan commented on openmdao/drivers/analysis_driver.py
> +        prob.driver.add_response('z', units='m')
```
    Responses are the outputs of the model to be recorded. These can be added
    using the standard driver interface.
```
This is not True, am I right?    `add_response` is not part of the standard driver interface...  Do you intend to add it to the base class?  or is it a special feature of this driver?

2025-02-10 18:59 UTC, naylor-b approved these changes

2025-02-14 15:42 UTC, merged